languageCode = "en"
languageName = "English"
weight = 1

title = "KeMiao's Blog"
 copyright = "Â© 2025 å…‹å–µçˆ±åƒå¤é¢ğŸ¤” <br /> å…¨ç«™çº¦ {{< wordCount \"all\" >}}"

[params]
  isoCode = "us"
  displayName = "US"
  rtl = false

  dateFormat = "2005 å¹´ 08 æœˆ 15 æ—¥"

  # mainSections = ["section1", "section2"]
   description = "I don't know..."
